[package]
name = "jmespath_optic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jmespath = { git = "https://github.com/waynevanson/jmespath.rs.git", branch = "public-modules" }
serde_json = "1.0.106"
