#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Copy manifest.json because BRAT doesn't follow symlinks
cp packages/data-entry/manifest.json manifest.json
git add manifest.json
git commit --amend --no-verify --no-edit --allow-empty
