#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm exec lint-staged --concurrent false

# Copy manifest.json because BRAT doesn't follow symlinks
cp packages/data-entry/manifest.json manifest.json
cp packages/data-entry/versions.json versions.json

# returns error code when there is a change in the file
git diff --exit-code -- manifest.json version.json 1>/dev/null ||
    git add manifest.json versions.json
